// users
export const GET_USERS = 'GET_USERS';
export const SELECTED_USER = 'SELECTED_USER';
export const LOGIN = 'LOGIN';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT = 'LOGOUT';
export const GET_QUESTIONS = 'GET_QUESTIONS';
export const REGISTER_VOTE_REQUEST = 'REGISTER_VOTE_REQUEST';
export const REGISTER_VOTE_SUCCESS = 'REGISTER_VOTE_SUCCESS';
